MvcSchoolWebApp/Controllers/CompanyDocController.cs
using MvcSchoolWebApp.Data;
using MvcSchoolWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace MvcSchoolWebApp.Controllers
{
    public class CompanyDocController : Controller
    {
        MessageCls msgobj = new MessageCls();
        public static string user_role;
        public static string user_id;
        public static string user_campus;
        public static string user_class;
        public static string user_section;
        public static string pagename;
        public static string popup_status;
        private Database.Database da = new Database.Database("Falconlocal");

        Data.data data = new data();
        public static string[] popupinfo = new string[3];
        public static List<Users> user_dtl;

        DatabaeseClass db;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (HttpContext.Session["User_Dtl"] != null)
            {
                user_dtl = (List<Users>)HttpContext.Session["User_Dtl"];
                base.OnActionExecuting(filterContext);
                user_role = HttpContext.Session["User_Role"].ToString();
                user_id = HttpContext.Session["User_Id"].ToString();

            }
            else
            {
                filterContext.Result = new RedirectResult("~/Login");
            }

        }
        // GET: CompanyDoc
        public ActionResult Index()
        {
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[68].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();

            db = new DatabaeseClass();
            CompanyDocModel model = new CompanyDocModel();
            model.dept = db.getDept();
            model.deptid = model.dept[0].Value;

            ViewBag.date = db.convertservertousertimezone(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile, CompanyDocModel model)
        {
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            if (list[68].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            DatabaseInsertClass din = new DatabaseInsertClass();
            model.user_id = user_id;

            if (model.deptid != null)
            {
                if (postedFile != null)
                {
                    if (postedFile.ContentLength <= 25000000)
                    {
                        var allowedExtensions = new[] { ".pdf", ".doc", ".docx", ".xlsx", ".xls" };
                        var checkextqension = Path.GetExtension(postedFile.FileName).ToLower();
                        string path = Server.MapPath("~/Uploads/CorporateDoc/");
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }

                        string query3 = "select isnull(max(docid)+01, 01) from corpdoc";
                        da.CreateConnection();
                        da.InitializeSQLCommandObject(da.GetCurrentConnection, query3);
                        da.OpenConnection();
                        model.increment = da.obj_sqlcommand.ExecuteScalar().ToString();
                        da.CloseConnection();

                        model.filename = Path.GetFileName(model.increment + " - " + postedFile.FileName);
                        model.imagepath = path + model.filename;
                        postedFile.SaveAs(model.imagepath);
                        din.InsertCompanyDoc(model);
                        if (popup_status == "Success")
                        {
                            ViewBag.Message = "File uploaded successfully.";
                            ViewBag.call_alert = "show_alert()";
                            ViewBag.message_popup = "File Successfully Uploaded";
                            ViewBag.cssclass = "alert-success";
                        }
                        else if (popup_status == "Rights")
                        {
                            ViewBag.Message = "No File Uploaded";
                            ViewBag.call_alert = "show_alert()";
                            ViewBag.message_popup = "You Do Not Have Rights";
                            ViewBag.cssclass = "alert-danger";
                        }
                        else
                        {
                            ViewBag.Message = "No File Uploaded";
                            ViewBag.call_alert = "show_alert()";
                            ViewBag.message_popup = "Found Some Error! Please Try Again";
                            ViewBag.cssclass = "alert-danger";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "File Size must be Less than 25 MB";
                        ViewBag.call_alert = "show_alert()";
                        ViewBag.message_popup = "No File Uploaded";
                        ViewBag.cssclass = "alert-danger";
                    }
                }
                else
                {
                    ViewBag.Message = "No File Uploaded";
                    ViewBag.call_alert = "show_alert()";
                    ViewBag.message_popup = "Please Select a File to Upload";
                    ViewBag.cssclass = "alert-danger";
                }
            }
            else
            {
                ViewBag.Message = "All Fields must be selected";
            }

            db = new DatabaeseClass();
            model.dept = db.getDept();
            model.deptid = model.dept[0].Value;
            ViewBag.date = model.date;
            return View(model);
        }

        public ActionResult AccountDoc()
        {
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[69].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            return View();
        }

        public JsonResult getJQGridJsonAccountDoc()
        {
            db = new DatabaeseClass();
            return Json(db.FillAccountDoc(user_role), JsonRequestBehavior.AllowGet);
        }

        public ActionResult HRDoc()
        {
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[70].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            return View();
        }

        public JsonResult getJQGridJsonHRDoc()
        {
            db = new DatabaeseClass();
            return Json(db.FillHRDoc(user_role), JsonRequestBehavior.AllowGet);
        }


        public ActionResult ERPDoc()
        {
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[71].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            return View();
        }

        public JsonResult getJQGridJsonERDoc()
        {
            db = new DatabaeseClass();
            return Json(db.FillERDoc(user_role), JsonRequestBehavior.AllowGet);
        }

        public ActionResult AOneDoc()
        {
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[72].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            return View();
        }

        public JsonResult getJQGridJsonAOneDoc()
        {
            db = new DatabaeseClass();
            return Json(db.FillAOneDoc(user_role), JsonRequestBehavior.AllowGet);
        }

        public ActionResult BOneDoc()
        {

MvcSchoolWebApp/Views/CompanyDoc/AOneDoc.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel
@{
    ViewBag.Title = "A-One Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Corporate Documents
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    A-One Documents
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="ibox-content" id="aonedoc_div">
                        <div class="row">
                            <div class="aonedoc_wrapper">
                                <table id="aonedoc_grid"></table>
                                <div id="aonedoc_pager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<script src=@Url.Content("~/Content/js/AOneDoc.js?n=1") asp-append-version="true"></script>

MvcSchoolWebApp/Views/CompanyDoc/AccountDoc.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel
@{
    ViewBag.Title = "Accounts Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Corporate Documents
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    Accounts Documents
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="ibox-content" id="accountdoc_div">
                        <div class="row">
                            <div class="accountdoc_wrapper">
                                <table id="accountdoc_grid"></table>
                                <div id="accountdoc_pager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>


<script src=@Url.Content("~/Content/js/AccountDoc.js?n=1") asp-append-version="true"></script>

MvcSchoolWebApp/Views/CompanyDoc/BOneDoc.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel
@{
    ViewBag.Title = "A-One Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Corporate Documents
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    B-One Documents
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="ibox-content" id="bonedoc_div">
                        <div class="row">
                            <div class="bonedoc_wrapper">
                                <table id="bonedoc_grid"></table>
                                <div id="bonedoc_pager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<script src=@Url.Content("~/Content/js/BOneDoc.js?n=1") asp-append-version="true"></script>

MvcSchoolWebApp/Views/CompanyDoc/ERPDoc.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel
@{
    ViewBag.Title = "ER Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Corporate Documents
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    ER Documents
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="ibox-content" id="erdoc_div">
                        <div class="row">
                            <div class="erdoc_wrapper">
                                <table id="erdoc_grid"></table>
                                <div id="erdoc_pager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<script src=@Url.Content("~/Content/js/ERPDoc.js?n=1") asp-append-version="true"></script>

MvcSchoolWebApp/Views/CompanyDoc/HRDoc.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel
@{
    ViewBag.Title = "HR Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div id="dvborder">
                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Corporate Documents
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    HR Documents
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="ibox-content" id="hrdoc_div">
                        <div class="row">
                            <div class="hrdoc_wrapper">
                                <table id="hrdoc_grid"></table>
                                <div id="hrdoc_pager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<script src=@Url.Content("~/Content/js/HRDoc.js?n=1") asp-append-version="true"></script>

MvcSchoolWebApp/Views/CompanyDoc/Index.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel
@{
    ViewBag.Title = "Upload Corporate Document";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Index", "CompanyDoc", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <section class="content">
        <!-- Info boxes -->
        <div class="row">

            <div class="col-lg-12">

                <div class="ibox float-e-margins">
                    <div id="dvborder">

                        <div class="ibox-title ">
                            <ul id="vert_menu">
                                <li>
                                    <input type="radio" id="r1" name="r">
                                    <label for="r1">
                                        Corporate Documents
                                    </label>
                                </li>
                                <li>
                                    <input type="radio" id="r2" name="r">
                                    <label for="r2">
                                        Upload Documents
                                    </label>
                                </li>
                            </ul>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <form role="form" id="uploadCompanyDocform" name="uploadCompanyDocform">
                                    <div class="row ">

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Department</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(m => m.deptid, Model.dept, "Department", new { @class = "form-control m-b", @name = "txtDeptCD", @id = "txtDeptCD", @required = true })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>
                                                    Date
                                                </label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.TextBoxFor(model => model.date, new { @Value = ViewBag.date, @class = "date-day form-control m-b", @name = "txtDateCD", @id = "txtDateCD", @required = true })
                                            </div>

                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div id="dvborder">
                        <div class="ibox-title ">
                        </div>
                        <div class="ibox-content">
                            <p style="font-family:initial; font-size:14px;">Note: You can only upload files less than 25 MB</p>
                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                <div class="form-control" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>
                                <span class="input-group-addon btn btn-default btn-file">
                                    <span class="fileinput-new">Select file</span>
                                    <span class="fileinput-exists">Change</span>
                                    <input type="file" name="postedFile">

                                </span>
                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>

                            </div>
                            <input type="submit" value="Upload" class="btn btn-sm btn-danger" id="btnuploadCompanyDoc" />
                            <span style="color:green">@ViewBag.Message</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

}

MvcSchoolWebApp/Views/CompanyDoc/displaydoc.cshtml
@model MvcSchoolWebApp.Models.CompanyDocModel

@{
    ViewBag.Title = "displaydoc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>displaydoc</h2>