MvcSchoolWebApp/Controllers/ResultController.cs
using CrystalDecisions.CrystalReports.Engine;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using MvcSchoolWebApp.Data;
using MvcSchoolWebApp.Models;

namespace MvcSchoolWebApp.Controllers
{
    public class ResultController : Controller
    {
        MessageCls msgobj = new MessageCls();
        public static string user_role;
        public static string user_id;
        public static string user_campus;
        public static string user_class;
        public static string user_section;
        public static List<Users> user_dtl;
        DatabaeseClass db;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (HttpContext.Session["User_Dtl"] != null)
            {
                user_dtl = (List<Users>)HttpContext.Session["User_Dtl"];
                base.OnActionExecuting(filterContext);
                user_role = user_dtl[0].user_earea;
                user_id = user_dtl[0].user_id;
            }
            else
            {
                filterContext.Result = new RedirectResult("~/Login");
            }
        }

        // GET: Result
        public ActionResult Index()
        {
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            List<SelectListItem> sl = new List<SelectListItem>();
            sl.Add(new SelectListItem
            {
                Text = "",
                Value = ""
            });

            db = new DatabaeseClass();
            DatabaseModel rusl = new DatabaseModel();

            rusl.campus = db.getcampus();
            rusl.classes = db.getclass(rusl.campus[0].Value, user_id);
            rusl.campusid = rusl.campus[0].Value;
            
            if (user_role == "5000" || user_role == "4000")
            {
                rusl.section = db.getsection(rusl.campus[0].Value, rusl.classes[0].Value, user_id);
                rusl.stdname = db.getstudentname(rusl.campus[0].Value, rusl.classes[0].Value, rusl.section[0].Value);
                rusl.subject = db.getsubject(rusl.campus[0].Value, rusl.classes[0].Value, rusl.section[0].Value, user_id);
                rusl.classesid = rusl.classes[0].Value;
                rusl.sectionid = rusl.section[0].Value;
                rusl.studentid = rusl.stdname[0].Value;
                rusl.subjectid = rusl.subject[0].Value;
            }
            else if (user_role == "1000" || user_role == "2000" || user_role == "3000")
            {
                rusl.classesid = "";
                //rusl.sectionid = "";
                //rusl.studentid = "";
                //rusl.subjectid = "";
                rusl.section = sl;
                rusl.stdname = sl;
                rusl.subject = sl;
            }

            

            return View(rusl);
        }
        
        public JsonResult fncresulttype(string dataToSave)
        {
            string getvalue = dataToSave;
            string url = "";
            try
            {
                Session["resulttype"] = getvalue;
                url = "/result/index";
            }
            catch (Exception)
            {
                Session["resulttype"] = "Weekly Test";
            }
            return Json(url, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Quiz()
        {
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            return View();
        }

        public ActionResult MidTerm()
        {
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            return View();
        }

        public ActionResult PublishResult()
        {
            MessageCls msgobj = new MessageCls();
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            DatabaseModel dm = new DatabaseModel();
            DatabaeseClass dc = new DatabaeseClass();
            dm.campus = dc.getcampus();
            dm.campusid = dm.campus[0].Value;

            //dm.classes = dc.getclass(dm.campus[0].Value, user_id);
            //dm.classesid = "";

            dm.module = dc.FillSubModule();
            dm.moduleid = "";

            return View(dm);
        }

        [HttpPost]
        public ActionResult PublishResult(DatabaseModel dm)
        {
            MessageCls msgobj = new MessageCls();
            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            DatabaeseClass dc = new DatabaeseClass();
            dm.campus = dc.getcampus();
            dm.campusid = dm.campusid;

            //dm.classes = dc.getclass(dm.campus[0].Value, user_id);
            //dm.classesid = dm.classesid;

            dm.module = dc.FillSubModule();
            dm.moduleid = dm.moduleid;

            ViewBag.resultlist = dc.getpublishresult(dm.campusid, dm.classesid, dm.moduleid);
            return View(dm);
        }

        [HttpPost]
        public JsonResult submitpublishresult(string campusid, string moduleid, string[] pubstat, string[] classid, string[] sectionid)
        {
            DatabaseInsertClass dc = new DatabaseInsertClass();
            dc.insertpublishresult(campusid, moduleid, pubstat, classid, sectionid);
            return Json(HomeController.popup_status, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult getstudentname(string campusId, string classId, string sectionId, string selectstudentnameid = null)
        {
            db = new DatabaeseClass();
            return Json(db.getstudentname(campusId, classId, sectionId));
        }

        [HttpPost]
        public JsonResult getClassJson(string campusId, string selectCityId = null)
        {
            db = new DatabaeseClass();
            return Json(db.getclass(campusId,user_id));
        }
       
        public JsonResult getSectionJson(String campusId, String classId, string selectsectionId = null)
        {
            db = new DatabaeseClass();
            return Json(db.getsection(campusId, classId,user_id));
        }

        [HttpPost]
        public JsonResult getsubjectJSON(String campusId, String classId, String sectionId, string nameId, string selectsubject = null)
        {
            db = new DatabaeseClass();
            return Json(db.getsubject(campusId, classId, sectionId, user_id));
        }
        public JsonResult getsessionJSON(String campusId, String classId, String sectionId, string nameId, string selectsubject = null)
        {
            db = new DatabaeseClass();
            return Json(db.FillSubject(campusId, classId, sectionId, user_id));
        }
        public JsonResult getfinalreports(string campusId, string classId, string sectionId, string moduleId)
        {
            db = new DatabaeseClass();
            return Json(db.FillFinalReports(campusId, classId, sectionId, moduleId));
        }


        public JsonResult getGridJson(string nameId, string subjectid, string campus, string classes, string section)
        {
            db = new DatabaeseClass();
            string resulttype = Session["resulttype"].ToString();
            return Json(db.FillWeeklyTest(nameId, subjectid,campus, classes, section,resulttype), JsonRequestBehavior.AllowGet);
        }

    }
}

MvcSchoolWebApp/Views/Result/Index.cshtml
@model MvcSchoolWebApp.Models.DatabaseModel
@{
    ViewBag.Title = "Index";
}
<script src=@Url.Content("~/Content/js/customjs.js?n=1") asp-append-version="true"></script>

<section class="content">
    <!-- Info boxes -->
    @*@using (Html.BeginForm())
    {*@

        <div class="row">

            <div class="col-lg-12">

                <div class="ibox float-e-margins">
                    <div id="dvborder">

                        <div class="ibox-title ">
                            <ul id="vert_menu">
                                <li>
                                    <input type="radio" id="r1" name="r">
                                    <label for="r1">
                                        Academics
                                    </label>
                                </li>
                                <li>
                                    <input type="radio" id="r2" name="r">
                                    <label for="r2">
                                        Student Performance
                                    </label>
                                </li>
                                <li>
                                    <input type="radio" id="r3" name="r">
                                    <label for="r3">
                                        @{
                                            try
                                            {
                                                @Session["resulttype"].ToString();
                                            }
                                            catch (Exception)
                                            {

                                                string url = "/dashboard";
                                                Response.Write("<script type='text/javascript'> window.location.href = '"+url+"' </script>");
                                                Response.Flush();
                                            }
                                        }
                                    </label>
                                </li>

                            </ul>


                        </div>

                        <div class="ibox-content">
                            <div class="row">
                                <form role="form" id="resultform" name="form">

                                    <div class="row ">
                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Campus</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(m => m.campusid, Model.campus, "Campus", new { @class = "form-control m-b", @name = "txtCampusRI", @id = "txtCampusRI", @required = true })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Class/Level</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(m => m.classesid, Model.classes, "Class/Level", new { @class = "form-control m-b", @name = "txtClassRI", @id = "txtClassRI", @required = true })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Section</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(m => m.sectionid, Model.section, "Section", new { @class = "form-control m-b", @name = "txtSectionRI", @id = "txtSectionRI", @required = true })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row ">
                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Student Name</label>
                                            </div>
                                            <div class="col-md-7">
                                               @{
                                                   @*if (HttpContext.Current.Session["User_Role"].ToString() == "student")
                                                   {
                                                    @Html.DropDownListFor(m => m.studentid, Model.stdname, "Student", new { @class = "form-control m-b", @name = "txtnameRI", @id = "txtnameRI", @required = true, @disabled = true })
                                                   }
                                                   else
                                                   {*@
                                                    @Html.DropDownListFor(m => m.studentid, Model.stdname, "Student", new { @class = "form-control m-b", @name = "txtnameRI", @id = "txtnameRI", @required = true })
                                                   @*}*@
                                            }
                                                
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Subject</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(m => m.subjectid, Model.subject, "Subject", new { @class = "form-control m-b", @name = "txtSubjectRI", @id = "txtSubjectRI", @required = true })
                                            </div>
                                        </div>
                                        @*<div class="col-md-4">
                                            <div class="col-md-5">
                                                <label>Session</label>
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(m => m.subjectid, Model.subject, "Session", new { @class = "form-control m-b", @name = "txtSessionRI", @id = "txtSessionRI", @required = true })
                                            </div>
                                        </div>*@
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="col-md-5 form-group">
                                                <input id="showGrid" type="submit" value="Submit" name="btnEnter" class="btn btn-sm btn-danger" />                                            
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox " id="quiz_div" style="display:none;">
                    <div id="dvborder">
                        <div class="ibox-content">
                            <div class="jqGrid_wrapper">
                                <table id="table_list_2"></table>
                                <div id="pager_list_2"></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    @*}*@
</section>

MvcSchoolWebApp/Views/Result/PublishResult.cshtml
@model MvcSchoolWebApp.Models.DatabaseModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Data Tables -->
<link href="~/Content/dbtheme/plugins/datatables/dataTables.bootstrap.css?n=1" rel="stylesheet">
<link href="~/Content/dbtheme/plugins/datatables/dataTables.responsive.css?n=1" rel="stylesheet">
<link href="~/Content/dbtheme/plugins/datatables/dataTables.tableTools.min.css?n=1" rel="stylesheet">

<style>
    /*.dataTables_length {
        margin-top:-3px;
    }*/
    .dataTables_filter {
        display: none;
    }

    .DTTT_container {
        display: none;
    }

    input[type=radio] {
        display: block;
    }

    .btn-getpublishresult {
        margin-top: 5px;
    }
    /*.dataTables_wrapper {
        margin-top:-34px;
    }*/
</style>
<script src=@Url.Content("~/Content/js/PublishResult.js?n=1") asp-append-version="true"></script>
<section class="content">
    <div class="animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><label>Publish Results</label></h5>
                    </div>

                    <div class="ibox-content">
                        @using (Html.BeginForm("PublishResult", "Result", FormMethod.Post))
                        {
                            <form id="publishresult1">
                                <div class="row">
                                    <div class="col-md-4">
                                        @Html.DropDownListFor(model => model.campusid, Model.campus, "Campus", new { @placeholder = "Campus", @class = "form-control", @id = "txtcampuspr", @name = "txtcampuspr", @required = true })
                                    </div>
                                    @*<div class="col-md-4">
                                            @Html.DropDownListFor(model => model.classesid, Model.classes, "Class", new { @placeholder = "Class", @class = "form-control", @id = "txtclasspr", @name = "txtclasspr", @required = true })
                                        </div>*@
                                    <div class="col-md-4">
                                        @Html.DropDownListFor(model => model.moduleid, Model.module, "Module", new { @placeholder = "Module", @class = "form-control", @id = "txtmodulepr", @name = "txtmodulepr", @required = true })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 col-md-offset-4 btn-getpublishresult">
                                        <input type="submit" value="Submit" class="btn btn-danger pull-right" />
                                    </div>
                                </div>
                            </form>
                        }
                        <form id="publishresult">
                            <table class="table table-striped table-bordered table-hover dataTables-example" summary="none">
                                <thead>
                                    <tr> 
                                        <th>Class</th>
                                        <th>Section</th>
                                        <th>Publish</th>
                                        <th>Un-Publish</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        var lst = ViewBag.resultlist as List<MvcSchoolWebApp.Data.PublishResultClass>;
                                        if (lst != null)
                                        {
                                            for (int i = 0; i < lst.Count; i++)
                                            {
                                                <tr class="gradeX">
                                                    <td> <input type="hidden" name="cls @i" value="@lst[i].classid" /> @lst[i].classes </td>
                                                    <td> <input type="hidden" name="sec @i" value="@lst[i].sectionid" /> @lst[i].section </td>
                                                    @if (lst[i].status == "rp")
                                                    {
                                                        <td class="center"><input type="radio" name="pub @i" value="publish" checked="checked" /></td>
                                                        <td class="center"><input type="radio" name="pub @i" value="unpublish" /></td>
                                                    }
                                                    else
                                                    {
                                                        <td class="center"><input type="radio" name="pub @i" value="publish" /></td>
                                                        <td class="center"><input type="radio" name="pub @i" value="unpublish" checked="checked" /></td>
                                                    }
                                                </tr>
                                            }
                                        }


                                    }
                                </tbody>
                                @*<tfoot>
                                        <tr>
                                            <th>Rendering engine</th>
                                            <th>Browser</th>
                                            <th>Platform(s)</th>
                                            <th>Engine version</th>
                                            <th>CSS grade</th>
                                        </tr>
                                    </tfoot>*@
                            </table>
                            <input type="submit" value="Publish" class="btn btn-danger" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>