MvcSchoolWebApp/Controllers/TMController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using iTextSharp.text;
using ClosedXML.Excel;
using iTextSharp.text.pdf;
using MvcSchoolWebApp.Data;
using MvcSchoolWebApp.Models;

namespace MvcSchoolWebApp.Controllers
{
    public class TMController : Controller
    {
        MessageCls msgobj = new MessageCls();
        public static string user_role;
        public static string user_id;
        public static string user_campus;
        public static string user_class;
        public static string user_section;
        public static string pagename;
        private Database.Database da = new Database.Database("Falconlocal");

        Data.data data = new data();
        private string camp_id;
        private string emp_id;
        public static string[] popupinfo = new string[3];
        public static List<Users> user_dtl;
        public Page Page { get; private set; }
        DataModel _context = new DataModel();
        DatabaeseClass db;
        public static System.IO.MemoryStream workStream;
        public static string strPDFFileName;
        // GET: TM

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (HttpContext.Session["User_Dtl"] != null)
            {
                user_dtl = (List<Users>)HttpContext.Session["User_Dtl"];
                base.OnActionExecuting(filterContext);
                user_role = HttpContext.Session["User_Role"].ToString();
                user_id = HttpContext.Session["User_Id"].ToString();

            }
            else
            {
                filterContext.Result = new RedirectResult("~/Login");
            }
        }

    
        [HttpGet]
        public ActionResult essTimeMgmt()
        {
            

            String dateId = "";
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[61].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            db = new DatabaeseClass();
            Timesheetmodal tsm = new Timesheetmodal();
            tsm.empname = db.FillSNSEmployee();
            tsm.empid = user_id;
            tsm.clientname = db.FillClient();
            tsm.date = db.convertservertousertimezone(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");
            tsm.time = db.convertservertousertimezone(DateTime.Now.ToString()).ToString("hh:mm tt");
            List<ESSModel> esslist = db.getemploydetail(user_id);
            bool isactive = db.isactiveuser(user_id, db.convertservertousertimezone(DateTime.Now.ToString()));
            tsm.empdesignation = esslist[0].design;
            tsm.empdepart = esslist[0].dept;
            if (isactive == true)
            {
                ViewBag.disabletimein = true;
                tsm.clientid = db.getclientid(user_id, dateId);
            }
            else
            {
                tsm.clientid = "150046";
            }
            return View(tsm);
        }

        [HttpGet]
        public ActionResult mssTimeMgmt()
        {
            String dateId = "";
            var list = HttpContext.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
            user_role = HttpContext.Session["User_Role"].ToString();
            user_id = HttpContext.Session["User_Id"].ToString();
            if (list[63].menustat != "X")
            {
                return RedirectToAction("Index", "dashboard");          //user has no right to access this page, return to dashboard
            }

            ViewBag.msglist = msgobj.GetNotifications();
            ViewBag.TotalNotification = msgobj.NumberofNotifications();
            db = new DatabaeseClass();
            Timesheetmodal tsm = new Timesheetmodal();
            tsm.empname = db.FillSNSEmployee();
            tsm.empid = user_id;
            tsm.clientname = db.FillClient();
            tsm.date = db.convertservertousertimezone(DateTime.Now.ToString()).ToString("dd-MMMM-yyyy");
            tsm.time = db.convertservertousertimezone(DateTime.Now.ToString()).ToString("hh:mm tt");
            List<ESSModel> esslist = db.getemploydetail(user_id);
            bool isactive = db.isactiveuser(user_id, db.convertservertousertimezone(DateTime.Now.ToString()));
            tsm.empdesignation = esslist[0].design;
            tsm.empdepart = esslist[0].dept;
            if (isactive == true)
            {
                ViewBag.disabletimein = true;
                tsm.clientid = db.getclientid(user_id, dateId);
            }
            else
            {
                tsm.clientid = "150046";
            }
            return View(tsm);
        }

        public JsonResult insertattendancerecord(string empid, string clientid, DateTime date, string time, string type, string remarks, string lattd, string lngtd)
        {
            DatabaseInsertClass dc = new DatabaseInsertClass();
            db = new DatabaeseClass();
            if (lattd != null || lngtd != null)
            {

                dc.InsertEmployeeAttendance(empid, clientid, date, time, type, remarks, lattd, lngtd);

                return Json(db.GetEmployeeAttendanceHistory(empid), JsonRequestBehavior.AllowGet);

            }
            else
            {

                return Json(false, JsonRequestBehavior.AllowGet);
            }


        }

        public void FetchDataFromDbAndGenerateExcelFile(DateTime infoEntered)
        {

            string constr = ConfigurationManager.ConnectionStrings["Falconlocal"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                con.Open();

                SqlCommand emp = new SqlCommand("select ep.empid  as id, concat(ep.firstname,ep.midname,ep.lastname)as name from emppers ep where  ep.delind <> 'X' and ep.empid not in (select empid from emp0351)", con);

                SqlDataReader emprdr = emp.ExecuteReader();


                string[] empid = new string[100];
                string[] empname = new string[100];
                string[] bdate = new string[31];
                string[] weekdaytxt = new string[31];

                int i = 0; int k = 0;
                while (emprdr.Read())
                {

                    empid[i] = emprdr["id"].ToString();
                    empname[i] = emprdr["name"].ToString();
                    i++;

                }

                emprdr.Close();
                string month = infoEntered.ToString("yyyy-MM") + "-25";
                string prevmonth = infoEntered.AddMonths(-1).ToString("yyyy-MM") + "-26";

                using (SqlCommand cal = new SqlCommand("select caldate, weekdaytxt from calndr where (calndr.caldate) >= '" + prevmonth + "' And   (calndr.caldate) <= '" + month + "' order by caldate", con))
                {
                    using (SqlDataReader rdr = cal.ExecuteReader())
                    {
                        while (rdr.Read())
                        {
                            DateTime myString = Convert.ToDateTime(rdr["caldate"]); //The 0 stands for "the 0'th column", so the first column of the result.
                                                                                    // Do somthing with this rows string, for example to put them in to a list
                            bdate[k] = myString.Date.ToString("MM/dd/yyyy");

                            weekdaytxt[k] = rdr["weekdaytxt"].ToString();

                            k++;
                        }

                    }
                }

                DataTable dt = new DataTable();

                for (int j = 0; j < empid.Length; j++)
                {
                    if (empid[j] != "" && empid[j] != null)
                    {


                        for (int l = 0; l < bdate.Length; l++)
                        {



                            using (SqlCommand cmd = new SqlCommand("select distinct emp0280.empid as empid, concat(emppers.firstname,emppers.midname,emppers.lastname) as name, CONVERT(date, emp0280.begdate) as Datee,CONVERT(time, emp0280.begdate) as TimeIn, CONVERT(time, emp0280.enddate) as TimeOut,eposhdr.postxt as Title, datename(dw, emp0280.begdate) as DayName, costorder.ordstxt as ClientName, emp0280.remarks from emp0280 inner join emppers on emppers.empid = emp0280.empid inner join emporg on emppers.empid = emporg.empid inner join eposhdr on emporg.pos =  eposhdr.pos inner join costorder on emp0280.clientid = costorder.costorder where 1=1 and emporg.delind = '' and emp0280.delind = '' and emppers.delind = '' and CAST(emp0280.begdate AS date) = '" + bdate[l] + "' and emp0280.empid = '" + empid[j] + "' ", con))
                            {
                                using (SqlDataReader sda = cmd.ExecuteReader())

                                {

                                    //while (sda.Read())
                                    //{

                                    //}

                                    if (sda.HasRows)
                                    {



                                        dt.Load(sda);
                                    }
                                    else
                                    {

                                        DataRow dr = null;
                                        int a = dt.Rows.Count;
                                        if (a > 0)
                                        {

MvcSchoolWebApp/Views/TM/DailyTimeSheet2.cshtml
@model MvcSchoolWebApp.Models.Timesheetmodal
@{
    ViewBag.Title = "DailyTimeSheet2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <!-- Info boxes -->
    <div class="row">

        <div class="col-lg-12">

            <div class="ibox float-e-margins">
                <div>

                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Time Management
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    Daily Time Sheet Report (Machine)
                                </label>
                            </li>
                        </ul>
                    </div>

                    <div class="ibox-content">
                        <div class="row">
                            <form role="form" id="frmcreatedailyrpt2">
                                <div class="row ">
                                    @{
                                        try
                                        {
                                            var list = HttpContext.Current.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
                                            if (list[0].earea.Trim() == "1000")
                                            {
                                                <div class="col-md-4">
                                                    <div class="col-md-5">
                                                        <label>Date</label>
                                                    </div>
                                                    <div class="col-md-7">

                                                        @Html.TextBoxFor(model => model.month, "Day", new { @Value = ViewBag.date, placeholder = "Date", @class = "date-day form-control m-b", @name = "DateTMR", @id = "DateTMR", @required = true, @onkeypress = "return false;", @autocomplete = "off" })
                                                    </div>
                                                </div>
                                            }
                                        }
                                        catch (Exception)
                                        {

                                            string url = "/dashboard";
                                            Response.Write("<script type='text/javascript'>");
                                            Response.Write("window.location.href = '" + url + "'</script>");
                                            Response.Flush();
                                        }

                                    }
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <input id="Btncreaterpt2" type="submit" value="Submit" name="btnEnter" class="btn btn-sm btn-default form-submitbtn" />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox " id="attendanceViewTMR_div">
                <div class="ibox-content">
                    <div class="attendanceViewTMR_jqGrid">
                        <table id="attendanceViewTMR_table"></table>
                        <div id="pager_list_TMR"></div>
                    </div>
                    @*@using (Html.BeginForm("CreatePdf", "TM", FormMethod.Post))
                        {*@

                    @try
                    {
                        var list = HttpContext.Current.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
                        if (list[0].earea.Trim() == "1000")
                        {

                            <div class="row ">
                                <div class="col-md-4">
                                    <div class="col-md-5">
                                        <input id="btn_createreport2" type="submit" class="btn btn-danger" name="name" value="Create Report" />
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    catch (Exception)
                    {

                        string url = "/dashboard";
                        Response.Write("<script type='text/javascript'>");
                        Response.Write("window.location.href = '" + url + "'</script>");
                        Response.Flush();
                    }


                </div>
            </div>
        </div>
    </div>
</section>
<script src=@Url.Content("~/content/js/DailyTimeSheet2.js") asp-append-version="true"></script>

MvcSchoolWebApp/Views/TM/Dailytimesheet.cshtml
@model MvcSchoolWebApp.Models.Timesheetmodal
@{
    ViewBag.Title = "Dailytimesheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <!-- Info boxes -->
    <div class="row">

        <div class="col-lg-12">

            <div class="ibox float-e-margins">
                <div >

                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Time Management
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                   Daily Time Sheet Report
                                </label>
                            </li>
                        </ul>
                    </div>

                    <div class="ibox-content">
                        <div class="row">
                            <form role="form" id="frmcreatedailyrpt">
                                <div class="row ">
                                    @{
                                        try
                                        {
                                            var list = HttpContext.Current.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
                                            if (list[0].earea.Trim() == "1000")
                                            {
                                                <div class="col-md-4">
                                                    <div class="col-md-5">
                                                        <label>Date</label>
                                                    </div>
                                                    <div class="col-md-7">

                                                       @Html.TextBoxFor(model => model.month, "Day", new { @Value = ViewBag.date, placeholder = "Date", @class = "date-day form-control m-b", @name = "DateTMR", @id = "DateTMR", @required = true, @onkeypress = "return false;", @autocomplete = "off" })
                                                    </div>
                                                </div>
                                            }
                                        }
                                        catch (Exception)
                                        {

                                            string url = "/dashboard";
                                            Response.Write("<script type='text/javascript'>");
                                            Response.Write("window.location.href = '" + url + "'</script>");
                                            Response.Flush();
                                        }

                                    }
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <input id="Btncreaterpt" type="submit" value="Submit" name="btnEnter" class="btn btn-sm btn-default form-submitbtn" />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox " id="attendanceViewTMR_div">
                <div class="ibox-content">
                    <div class="attendanceViewTMR_jqGrid">
                        <table id="attendanceViewTMR_table"></table>
                        <div id="pager_list_TMR"></div>
                    </div>
                    @*@using (Html.BeginForm("CreatePdf", "TM", FormMethod.Post))
                        {*@

                    @try
                    {
                        var list = HttpContext.Current.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
                        if (list[0].earea.Trim() == "1000")
                        {

                            <div class="row ">
                                <div class="col-md-4">
                                    <div class="col-md-5">
                                        <input id="btn_createreport" type="submit" class="btn btn-danger" name="name" value="Create Report" />
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    catch (Exception)
                    {

                        string url = "/dashboard";
                        Response.Write("<script type='text/javascript'>");
                        Response.Write("window.location.href = '" + url + "'</script>");
                        Response.Flush();
                    }


                </div>
            </div>
        </div>
    </div>
</section>
<script src=@Url.Content("~/Content/js/DailyTmshtReport.js?n=2") asp-append-version="true"></script>

MvcSchoolWebApp/Views/TM/DisplayConveyanceReport.cshtml
@model MvcSchoolWebApp.Models.Timesheetmodal

@{
    ViewBag.Title = "DisplayConveyanceReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <!-- Info boxes -->
    <div class="row">

        <div class="col-lg-12">

            <div class="ibox float-e-margins">
                <div >

                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Time Management
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                    Employee Conveyance Report
                                </label>
                            </li>
                        </ul>
                    </div>

                    <div class="ibox-content">
                        <div class="row">
                            <form role="form" name="ViewReportECRForm" id="ViewReportECRForm">
                                <div class="row ">                                    
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <label>Pick a Month</label>
                                        </div>
                                        <div class="col-md-7">
                                            @Html.TextBoxFor(model => model.month, "Month", new { @Value = DateTime.Now.ToString("MMMM yyyy"), placeholder = "Month", @class = "date-month form-control m-b", @name = "ViewReportMonthECR", @id = "ViewReportMonthECR", @required = true, @onkeypress = "return false;", @autocomplete = "off" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <input id="btnVeiwReportECR" type="submit" value="Submit" name="btnVeiwReportECR" class="btn btn-sm btn-default form-submitbtn" />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src=@Url.Content("~/Content/js/TimeSheetReport.js?n=2") asp-append-version="true"></script>

MvcSchoolWebApp/Views/TM/Index.cshtml
@model MvcSchoolWebApp.Models.Timesheetmodal
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<script src=@Url.Content("~/Content/dbtheme/bootstrap/js/bootstrap-datepicker.js?n=1") asp-append-version="true"></script>*@
@*<script src=@Url.Content("~/Content/js/bootstrap-datetimepicker.min.js") asp-append-version="true"></script>*@


<section class="content">
    <!-- Info boxes -->
    <div class="row">

        <div class="col-lg-12">

            <div class="ibox float-e-margins">
                <div>

                    <div class="ibox-title ">
                        <ul id="vert_menu">
                            <li>
                                <input type="radio" id="r1" name="r">
                                <label for="r1">
                                    Time Managements
                                </label>
                            </li>
                            <li>
                                <input type="radio" id="r2" name="r">
                                <label for="r2">
                                   Employee Time Sheet Report
                                </label>
                            </li>
                        </ul>
                    </div>

                    <div class="ibox-content">
                        <div class="row">
                            <form role="form" name="viewAttendanceTMRForm" id="viewAttendanceTMRForm">
                                <div class="row ">
                                    @{
                                        try
                                        {
                                            var list = HttpContext.Current.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
                                            if (list[0].earea.Trim() == "1000")
                                            {
                                                <div class="col-md-4">
                                                    <div class="col-md-5">
                                                        <label>Employee Name</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        @Html.DropDownListFor(m => m.empid, Model.empname, "Employee", new { @class = "form-control m-b", @name = "txtEmpNameTMR", @id = "txtEmpNameTMR", @required = true })
                                                    </div>
                                                </div>
                                            }
                                        }
                                        catch (Exception)
                                        {

                                            string url = "/dashboard";
                                            Response.Write("<script type='text/javascript'>");
                                            Response.Write("window.location.href = '" + url + "'</script>");
                                            Response.Flush();
                                        }

                                    }
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <label>Pick a Month</label>
                                        </div>
                                        <div class="col-md-7">
                                            @Html.TextBoxFor(model => model.month, "Month", new { @Value = DateTime.Now.ToString("MMMM yyyy"), placeholder = "Month", @class = "date-month form-control m-b", @name = "ViewAttendaceDateTMR", @id = "ViewAttendaceDateTMR", @required = true, @autocomplete = "off" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <input id="veiwAttendanceTMR" type="submit" value="Submit" name="btnEnter" class="btn btn-sm btn-default form-submitbtn" />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox " style="border: 1px solid #d2d6de; display:none;" id="attendanceViewTMRA_div_c">
                <div class="ibox-content">
                    <div class="attendanceViewTMR_jqGrid_c">
                        <table id="attendanceViewTMRA_table_c"></table>
                        <div id="pager_list_TMR"></div>
                    </div>
                    @*@using (Html.BeginForm("CreatePdf", "TM", FormMethod.Post))
                    {*@

                        @try
                        {
                            var list = HttpContext.Current.Session["User_Rights"] as List<MvcSchoolWebApp.Models.LoginModel>;
                            if (list[0].earea.Trim() == "1000")
                            {

                                <div class="row ">
                                    <div class="col-md-4">
                                        <div class="col-md-5">
                                            <input id="btn_createreport" type="submit" class="btn btn-danger" name="name" value="Create Report" />
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                        catch (Exception)
                        {

                            string url = "/dashboard";
                            Response.Write("<script type='text/javascript'>");
                            Response.Write("window.location.href = '" + url + "'</script>");
                            Response.Flush();
                        }

                 
                </div>
            </div>
        </div>
    </div>
    <div class="modal inmodal" id="empTMRA_dialogue" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Are you sure you want to Continue?</h4>
                </div>
                <div class="modal-footer" style="margin-top:0;">
                    <form id="empTMRA_dialogue_frm" name="popupform" method="post" action="">
                        <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                        <input type="submit" name="submit" value="Proceed" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<script src=@Url.Content("~/Content/js/TimeSheetReport.js?n=3") asp-append-version="true"></script>